Repository eth-classic/go-ethereum, pull requests merged in 2019-06, with the labels that each got.

#57 makefile: fix version string
  Makefile
Labels: PR: Needs Review, Type: Build

#56 Dockerfile configuration
  Dockerfile
Labels: PR: In Progress, Type: Build

#59 docs: update readme
  README.md
Labels: PR: Looks Good, Type: Documentation

#64 ci: prepare assets for release
  .circleci/config.yml
Labels: PR: Needs Review, Type: Build

#62 Receipt fixes and state trie clearing detail
  core/block_validator.go
  core/chain_manager.go
  core/database_util_test.go
  core/multivm_processor.go
  core/state_processor.go
  core/types/receipt.go
  miner/worker.go
Labels: PR: Looks Good, Priority: 0 Consensus, Type: Core

#71 Adding Ethereum tests submodule to CircleCI tests
  .circleci/config.yml
Labels: PR: Looks Good, Type: Tests

#69 Remove difficulty bomb for Atlantis difficulty calculation
  core/block_validator.go
  tests/difficulty_test_util.go
Labels: PR: Looks Good, Priority: 2 High, Type: Core, Type: Tests

#72 ci: only build releases on tags
  .circleci/config.yml
Labels: PR: Looks Good, Type: Build

#73 Tests config fix
  core/block_validator_test.go
  core/state_processor_test.go
Labels: PR: Looks Good, Type: Tests

#63 config: fix atlantis mainnet block number
  core/assets/assets.go
  core/config/mainnet.json
Labels: PR: Looks Good, Priority: 0 Consensus, Type: Meta

#77 core: activate atlantis on mainnet block 8772000
  core/assets/assets.go
  core/config/mainnet.json
Labels: PR: Needs Review, Priority: 0 Consensus, Type: Core

#80 docs: badges badges badges badges
  README.md
Labels: PR: 5 Looks Good, Priority: 5 Medium, Type: Documentation
